name: CrashClaim
version: ${version}
description: A modern advanced user oriented claiming system
author: Chasewhip
main: net.crashcraft.crashclaim.CrashClaim
api-version: '1.20'
dependencies:
  server:
    Vault:
      required: false
    GriefPrevention:
      required: false
    WorldGuard:
      required: false
    PlaceholderAPI:
      required: false
    Multiverse-Core:
      required: false
    LuckPerms:
      required: false
    QuickShop-Hikari:
      required: false
    DeluxeSellwands:
      required: false